version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: welllist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./server:/app/server
      - ./client:/app/client
    environment:
      DB_USER: postgres
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: welllist
      # 필요한 경우 추가 환경변수
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: 