version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: welllist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app/server
      - ./client:/app/client
    environment:
      DB_USER: postgres
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: welllist
    depends_on:
      - db

  react:
    image: node:18
    working_dir: /app
    command: >
      bash -c "
        echo 'Setting up React development environment...' &&
        npm install -g vite &&
        npm install &&
        echo 'Starting Vite development server...' &&
        npx vite --host 0.0.0.0
      "
    ports:
      - "5173:5173"
    volumes:
      - ./client-react:/app
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://fastapi:8000
    depends_on:
      - fastapi
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5173 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: